# Generated by Django 3.2 on 2021-10-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_student_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelAndSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_and_section', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Level and Section',
                'verbose_name_plural': 'Level and Sections',
            },
        ),
    ]
